### ISSUE TITLE
Error in function gl.report.parent.offspring

### ISSUE THREAD

**Issue by cyy9363** [green-striped-gecko/dartR#101]
Dear dartR developer, 

I encountered the following error when using `gl.report.parent.offspring()`
The codes are like this:

```{r}
dartfile <- "0_Dart2row.csv"
meta <- "IndFile.csv"
lastmetric <- "RepAvg"

gl <- gl.read.dart(filename = "0_Dart2row.csv",  ind.metafile = "IndFile.csv", topskip = 6, lastmetric = "RepAvg")
gl.report.parent.offspring(gl)
```
It gives the following verbose then an error:

Starting gl.report.parent.offspring 
  Processing a SNP dataset
  Generating null expectation for distribution of counts of pedigree incompatability
  Identifying outliers with lower than expected counts of pedigree inconsistencies
  Standard boxplot, no adjustment for skewness
  Identifying outlying pairs
> Error in pnorm(mean = mean(count, na.rm = TRUE), sd = sd(count, na.rm = TRUE), : Non-numeric argument to mathematical function

I could only see a boxplot, no further information.

From the "gl.report.parent.offspring.r" script I think there might be a problem in the variable "count" (non-numeric value)? Or does that mean the dataset contains no parent-offspring relationship?

The same error shows up when using  `gl.filter.parent.offspring()` as well.

Could you please help me debugging the issue? I can provide the file if required. Thank you in advance!
Eryn

**Comment by mijangos81** [comment]
Hi Eryn,

It would be great if you could provide a dummy data or a subsample of your dataset.

Cheers,
Luis

**Comment by cyy9363** [comment]
Hi Luis,

Attached are the dummy files. I read the files with the following codes:

`test <- gl.read.dart(filename = "0_Dart2row_copy.csv",  ind.metafile = "IndFile_copy.csv", topskip = 6, lastmetric = "RepAvg")`

[testfile.zip](https://github.com/green-striped-gecko/dartR/files/6119803/testfile.zip)

Thank you in advance!

Eryn

**Comment by mijangos81** [comment]
Hi Eryn,

The problem was that when no outliers were found the function crashed. It is now fixed in the attached function. To use this function please unzip it and move it to your working directory. Then in the command line of R type:

> library(dartR)
> source(“gl.report.parent.offspring.r")
> test <- gl.read.dart(filename = "0_Dart2row_copy.csv", ind.metafile = "IndFile_copy.csv", topskip = 6, lastmetric = "RepAvg")
> test_res <- gl.report.parent.offspring(test)

Regards,
Luis

[gl.report.parent.offspring.r.zip](https://github.com/green-striped-gecko/dartR/files/6134350/gl.report.parent.offspring.r.zip)

**Comment by cyy9363** [comment]
Hi Luis, 

Thanks! The `gl.report.parent.offspring` funtion is working now and I can see the barplot!

Eryn
