### ISSUE TITLE
Revise gl.percent.freq.r

### ISSUE THREAD

**Issue by biomatix** [green-striped-gecko/dartR#105]
gl.percent.freq.r is exceptionally slow, and needs revision of its central algorithm, as this script is used by a number of other scripts and is adding substantially and unnecessarily to the computational time.

**Comment by mijangos81** [comment]
function has been updated to be faster. this function has now been merged with dev. 

time used by previous function 
user         system    elapsed 
158.483   4.685      163.240 

time used by updated function
user       system    elapsed 
13.599    1.052        14.665 

#106
