### ISSUE TITLE
Fst’s between population

### ISSUE THREAD

**Issue by laiajulianamu** [green-striped-gecko/dartR#186]
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': 'list' object cannot be coerced to type 'double'

**Comment by mijangos81** [comment]
Hi Laia,

- Could you please send us the actual code that you used that produced the error?
- Are you using DArT data?

Cheers,
Luis

**Comment by laiajulianamu** [comment]
Hi Luis 

gd <- as.matrix(as.dist(gl.fst.pop(gl))) 

Yes, I am using DArT data

**Comment by mijangos81** [comment]
you can try:
gd <- as.matrix(as.dist(gl.fst.pop(gl)$Fsts))

**Comment by laiajulianamu** [comment]
Thank you so much!!!
