### ISSUE TITLE
Bug in gl2fasta -- output fasta records differ in length

### ISSUE THREAD

**Issue by arthurgeorges** [green-striped-gecko/dartR#4]
Output fastA records differ in length. Rarely, records are one base short. Suggest looking at script behaviour when SNPosition = 1 or SNPosition is the last base of the seqeunce tag.  @green-striped-gecko

**Comment by green-striped-gecko** [comment]
corrected for method 1 and 2. method 3 needs to check for "outlier" snp position as well (see method 1)

**Comment by green-striped-gecko** [comment]
done
