### ISSUE TITLE
gl.outflank() function na.rm error

### ISSUE THREAD

**Issue by ghost** [green-striped-gecko/dartR#459]
Dear dartR developers,

I encountered the following error when using gl.outflank():

`> gl.outflank(data, plot = TRUE)`
Starting gl2gi 
  Processing genlight object with SNP data
Matrix converted.. Prepare genind object...
Completed: gl2gi 
Calculating FSTs, may take a few minutes...
Error in quantile.default(pi0, prob = 0.1) : 
  missing values and NaN's not allowed if 'na.rm' is FALSE

The function works perfectly on the toy data set platypus.gl.

Do you know what the issue could be?

This is an overview of my data set (data.gl)
 /// GENLIGHT OBJECT /////////

 // 169 genotypes,  3,944 binary SNPs, size: 14.9 Mb
 0 (0 %) missing data

 // Basic content
   @gen: list of 169 SNPbin
   @ploidy: ploidy of each individual  (range: 2-2)

 // Optional content
   @ind.names:  169 individual labels
   @loc.names:  3944 locus labels
   @loc.all:  3944 alleles
   @position: integer storing positions of the SNPs
   @pop: population of each individual (group size range: 4-8)
   @other: a list containing: loc.metrics  ind.metrics  latlon  loc.metrics.flags  verbose  history

Thank you,

**Comment by mijangos81** [comment]
Hi,

sorry for the late response, when don't check the issues in github very often. 

The best way to contact us would be our google groups: https://groups.google.com/g/dartr?pli=1 

Could you send me a subset of your data that replicates the behaviour you see to luis.mijangos@gmail.com. The code below shows how you can subset your data and save it. Please send me the file “test.rds” as in the code example below and also the code you are using. 

library(dartR)
# subset loci
# you can increase the number of loci to subsample for example n=400
test <- gl.subsample.loci([your_data.gl](http://your_data.gl/),n=200,method = "random")
#subset individuals
# you can increase the number of individuals to subsample by using for example indNames(test)[1:20]
test <- gl.keep.ind(test,ind.list = indNames(test)[1:10])
# saving object in the working directory
saveRDS(test, "test.rds")

Regards,
Luis
