### ISSUE TITLE
gl.pcoa.plot no longer allows saving plot to use other ggplot2 features

### ISSUE THREAD

**Issue by fernandabiologia** [green-striped-gecko/dartR#486]
Hi,

I'm just revisiting some old code where I used to save a gl.pcoa.plot to an object, so I could use ggplot2 to further manipulate the plot. 

# code example
p <- gl.pcoa.plot2(pcoa_postfilt, gl.filt6, pop.labels="pop", pt.colors=col,  xaxis=1, yaxis=2)

p <- p + theme_bw() +
  theme(panel.border = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.title=element_text(size=22),
        axis.text=element_text(size=20),
        axis.title.y=element_text(vjust=1.5),
        axis.title.x=element_text(vjust=-0.5),
        axis.line = element_line(),
        legend.title = element_blank()) 

I'm now using the latest version of DartR and when I try to save the pcoa to an object it returns NULL. It would be nice to have that capability back.  Is that something that could be added in future versions?

Thanks.

**Comment by mijangos81** [comment]
Hi,

Please see code below.

Cheers,
Luis

library(dartR)
library(ggthemes)

test <- platypus.gl
pcoa <- gl.pcoa(test)
# running the function with save2tmp = TRUE to save the plot and tables in 
# the temporal directory
gl.pcoa.plot(pcoa,test,save2tmp = TRUE)
# listing the plots and tables in tempdir
gl.list.reports()
# choosing the plot or table to retrieve
res <- gl.print.reports(1)

PopColours <- gl.select.colors(test,library =  "brewer",palette = "Set3",)

res+
theme_bw() +
  theme(axis.title = element_text(size = 14)) +
  theme(axis.text.x = element_text(size = 12)) +
  theme(axis.text.y = element_text(size = 12)) +
  theme(axis.ticks = element_line (size = 1)) +
  theme(panel.border = element_rect(color = "black", fill = NA, size = 1.8)) +
  scale_colour_manual(values = PopColours) +
  theme(legend.title = element_text(colour = "black",  size = 14)) +
  labs(col = "Site") +
  theme(legend.text = element_text(colour = "black", size = 12, face = "bold")) +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  guides(colour = guide_legend(override.aes = list(size=4))) +
  geom_point(x = -26.148284, y = -12.758024, color = "#0000B4")

**Comment by fernandabiologia** [comment]
Than you. It worked perfectly.
