### ISSUE TITLE
Add trimmed sequences to  testset.gl

### ISSUE THREAD

**Issue by arthurgeorges** [green-striped-gecko/dartR#5]
testset.gl does not have trimmed seqeunces in it, so some of the examples will fall over. May need to recreate the testset.gl.

**Comment by green-striped-gecko** [comment]
do you have the trimmed sequences for that file still?

**Comment by arthurgeorges** [comment]
No sadly. 

A

**Comment by arthurgeorges** [comment]
Here is the testset.gl with the trimmed sequences added.
[testset.zip](https://github.com/green-striped-gecko/dartR/files/888232/testset.zip)
