### ISSUE TITLE
gl.read.dart produces error during data import

### ISSUE THREAD

**Issue by nrcombs** [green-striped-gecko/dartR#511]
When attempting to import a DArT dataset using gl.read.dart, I get the following error:

Starting gl.read.dart 
Starting utils.read.dart 
  Reading in the SNP data
Error in utils.read.dart(filename = filename, nas = nas, topskip = topskip,  : 
  object 'tdummy' not found

My code is as follows:
`data.gl = dartr::gl.read.dart(filename = "infile.csv", covfilename = "infile.meta.csv", topskip = 0, recalc = TRUE, mono.rm = TRUE, verbose = 5)`

I am running dartr v2.0.4 in R v4.2.0. I've previously imported this dataset with dartr::gl.read.dart and haven't had issues, but it's been a couple of months. After encountering this issue, I updated my install of dartr from CRAN then ran gl.install.vanilla.dartR()

**Comment by mijangos81** [comment]
Can you install the developing version of dartR as shown below and try again.

library(dartR)
gl.install.vanilla.dartR(flavour= "dev")

Cheers,
Luis

**Comment by nrcombs** [comment]
Thanks for the suggestion! I've installed the development version, but still running into the same problem. 

`library(dartR)
gl.install.vanilla.dartR(flavour= "dev")

data.gl = gl.read.dart(filename="infile.csv", covfilename="infile.metadata.csv", topskip = 0, recalc = TRUE, mono.rm = TRUE, verbose = 5)

Starting gl.read.dart 
[dartR vers. 2.1.4 Build = Jody ]
Starting utils.read.dart 
[dartR vers. 2.1.4 Build = Jody ]
  Reading in the SNP data
Error in utils.read.dart(filename = filename, nas = nas, topskip = topskip,  : 
  object 'tdummy' not found`

**Comment by mijangos81** [comment]
can you try:

data.gl = gl.read.dart(filename="infile.csv", covfilename="infile.metadata.csv", mono.rm = TRUE, verbose = 5)

**Comment by nrcombs** [comment]
When I remove both the topskip and recalc arguments, I get the following error: 

`Starting gl.read.dart`
`[dartR vers. 2.1.4 Build = Jody ]`
`Starting utils.read.dart` 
`[dartR vers. 2.1.4 Build = Jody ]`
  `Topskip not provided.`
 `Error in utils.read.dart(filename = filename, nas = nas, topskip = topskip,  : `
  `Could not determine the number of rows that need to be skipped. Please provide it manually by setting the topskip` `parameter.`

I tried again with just the recalc argument removed, and got the tdummy error again that I described above.

**Comment by nrcombs** [comment]
Will do, thanks Luis!
