### ISSUE TITLE
gl.report.heterozygosity() no longer reporting number of polymorphic loci per pop

### ISSUE THREAD

**Issue by fernandabiologia** [green-striped-gecko/dartR#513]
Hi,

I used to be able to get number of polymorphic loci per population with the function gl.report.heterozygosity(gl, method = "pop", verbose=3). But in the new version when I call this function all I get is the same number of loci across all population (which is the total number of loci across the whole dataset). Is there a new function to get this information? Or could this be an issue with the gl.report.heterozygosity() function in the new dartR version? 

Thanks,

Fernanda.

**Comment by mijangos81** [comment]
Hi Fernanda,

The function now reports the number of polymorphic loci, monomorphic loci and loci with all missing data.

To use this updated function you should install the developing version of dartR as shown below:

> library(dartR)
> gl.install.vanilla.dartR(flavour = "dev")

Cheers,
Luis

**Comment by fernandabiologia** [comment]
Hi Luis,

Thank you. It worked perfectly. 

Cheers,

Fernanda.
