### ISSUE TITLE
Issues with ggplot2 3.4.0

### ISSUE THREAD

**Issue by thomasp85** [green-striped-gecko/dartR#521]
Hi

We recently released ggplot2 3.4.0 and while we didn’t detect issues with dartR during our tests, CRAN has seen issues after release. This mail is to notify you about this and offer help if there are any issues you have trouble fixing

Kind regards
Thomas Lin Pedersen, ggplot2 maintainer

**Comment by mijangos81** [comment]
Hi Thomas,

Thank you for contacting us. 

The problem was with the package ggtern, which we have already fixed. 

We will soon submit our package to CRAN. 

Cheers,
Luis
