### ISSUE TITLE
gl.outflank settings

### ISSUE THREAD

**Issue by ollybolly** [green-striped-gecko/dartR#54]
Hi Bernd & Arthur,
I was just running gl.outflank and realised that one of the settings "LeftTrimFraction" I'd written as "eftTrimFraction" - but its didn't give me any error.  Is that because you've built in some cunning typo-tolerance, or its not reading that setting? Cheers, Olly

**Comment by green-striped-gecko** [comment]
If a parameter cannot match (and I think if not started correctly it does not), then the default is used.
LeftTrimFraction=0.05.

So most likely this was the case in your run.
