### ISSUE TITLE
Error in gl.filter.secondaries 

### ISSUE THREAD

**Issue by juliannasantoseco** [green-striped-gecko/dartR#563]
Hello all!
I'm trying to use gl.filter.secondaries (x, method="best") 

And found this (persistent in different datasets):

Error in strsplit(as.character(x2@other$loc.metrics$AlleleID), "\\|") : 
  object 'x2' not found

Could anyone shed light on this issue?

Cheers,

**Comment by mijangos81** [comment]
Hi,

Thank you for informing us about this bug. The fix is available in the dartR beta version, which you may install by using the code below:

> library(dartR)
> gl.install.vanilla.dartR(flavour = "beta")

Cheers,
Luis

**Comment by juliannasantoseco** [comment]
Oh yes! It seems to be fixed!
Thank you heaps!
