### ISSUE TITLE
gl2vcf issue

### ISSUE THREAD

**Issue by burbrink** [green-striped-gecko/dartR#583]
Hello, 

I am trying to convert a genlight to a VCF and keep getting the following error. I can run your test example, so it doesn't seem to be a plink issue. I have attached my file. Thanks for any help you can provide!
gl2vcf(glSW, outfile="6_SW_Corns_vcf",plink_path= "/Users/frankburbrink/Dropbox/Ecological_Speciation/Milks/plink_mac_20230116/",outpath=  "/Users/frankburbrink/Dropbox/Ecological_Speciation/Milks/plink_mac_20230116/")

Starting gl2vcf 
  Processing genlight object with SNP data
  Chromosome information is not present in the slot 'chromosome'. Setting '0' as the name chromosome for all the SNPs.
Starting gl2plink 
  Processing genlight object with SNP data
**Error in xx[i, ii] <- hets[ii] : 
  number of items to replace is not a multiple of replacement length**

[glSW_try.zip](https://github.com/green-striped-gecko/dartR/files/10761142/glSW_try.zip)

**Comment by mijangos81** [comment]
Hi, 

How did you read your data into dartR?
It might be that you don’t have information in the slot “loc.all”.

What is printed when you type:
gl$loc.all

If you don’t have information in this slot, you can create a dummy variable, as below:
gl$loc.all <- rep("G/C",nLoc(gl))

Then try again running the function.

Cheers,
Luis

**Comment by burbrink** [comment]
Hi Luis,

To the rescue again. Thanks so much.

Just a small correction to your solution:

gl$loc.all<- rep("G/C",gl@n.loc)
