### ISSUE TITLE
gl.report.monomorphs value incorrect

### ISSUE THREAD

**Issue by RobWhite100** [green-striped-gecko/dartR#61]
I think I may have found a bug in gl.report.monomorphs.
When running gl.report.monomorphs after running gl.filter.monomorphs on a genlight object the report  indicates that there are still monomorphs present in the object.
Looking at the code in gl.report.monomorphs, it appears that when a loci has only 1 (heterozygote) values, or a combination of 1 and NA, (ie. no 0 or 2 present) it is being counted as monomorphic:
line 50: **c[i] <- all(xmat[,i]==1,na.rm=TRUE)**
which is different to the code in gl.filter.monomorphs used to determine monomorphs:
line 46: **a[i] <- all(xmat[,i]==0,na.rm=TRUE) || all(xmat[,i]==2,na.rm=TRUE)**
I have used a genlight object and excel to test this and can provide files if required.
Regards
Rob

**Comment by arthurgeorges** [comment]
Fortunately, all heterozygous loci does not happen too often, but not good in any case. Error slipped the net.  Try this amended script (github won't let me upload it). Will add it to the next update. Thanks so much for bringing it to our attention.

#' Report monomorphic loci, including those with all NAs
#'
#' This script reports the number of monomorphic loci from a genlight \{adegenet\} object
#'
#' A DArT dataset will not have monomorphic loci, but they can arise when populations or individuals are deleted.
#' Retaining monomorphic loci may unnecessarily increases the size of the dataset.
#'
#' @param x -- name of the input genlight object [required]
#' @param probar -- if TRUE, a progress bar will be displayed for long loops [default = TRUE]
#' @return NULL
#' @import adegenet plyr utils
#' @export
#' @author Arthur Georges (Post to \url{https://groups.google.com/d/forum/dartr})
#' @examples
#' gl2 <- gl.report.monomorphs(testset.gl)

gl.report.monomorphs <- function (x, probar=FALSE) {
  
# ERROR CHECKING
  
  if(class(x)!="genlight") {
    cat("Fatal Error: genlight object required for gl.report.repavg!\n"); stop()
  }
  # Work around a bug in adegenet if genlight object is created by subsetting
  x@other$loc.metrics <- x@other$loc.metrics[1:nLoc(x),]
  
# FLAG SCRIPT START
    cat("Starting gl.report.monomorphs: Reporting frequency of monomorphic loci\n")

  cat("Identifying monomorphic loci\n")
# Create vectors to hold test results
  # homozygote reference
  a <- vector(mode="logical", length=nLoc(x))
  for (i in 1:nLoc(x)) {a[i] <- FALSE}
  # homozygote alternate
  b <- vector(mode="logical", length=nLoc(x))
  for (i in 1:nLoc(x)) {b[i] <- FALSE}
  # heterozygote 
  c <- vector(mode="logical", length=nLoc(x))
  for (i in 1:nLoc(x)) {c[i] <- FALSE}
  # NA
  d <- vector(mode="logical", length=nLoc(x))
  for (i in 1:nLoc(x)) {d[i] <- FALSE}
  
# Set up the progress counter
  if(probar) {
    pb <- txtProgressBar(min=0, max=1, style=3, initial=0, label="Working ....")
    getTxtProgressBar(pb)
  }
# Identify polymorphic, monomorphic and 'all na' loci
  # Set a,b,c <- TRUE if monomorphic, d <- TRUE if all NAs
  xmat <-as.matrix(x)
  for (i in (1:nLoc(x))) {
    if (all(is.na(xmat[,i]))) {
      d[i] <- TRUE
      a[i] <- FALSE
      b[i] <- FALSE
      c[i] <- FALSE
    } else {
      d[i] <- FALSE
      a[i] <- all(xmat[,i]==0,na.rm=TRUE)
      b[i] <- all(xmat[,i]==2,na.rm=TRUE)
      c[i] <- all(xmat[,i]==1,na.rm=TRUE)
    }
    if (probar) {setTxtProgressBar(pb, i/nLoc(x))}
  }
  # Calculate the number of monomorphic loci with values
  monom <- sum(a,na.rm=TRUE) + sum(b,na.rm=TRUE)
  allna <- sum(d,na.rm=TRUE)
  polym <- nLoc(x) - (monom + allna)
  cat("\nBreakdown of", nLoc(x), "loci\n")
  cat("  Monomorphic loci:", monom,"\n  Polymorphic loci:", polym, "\n  Loci with no scores (all NA):" , allna ,"\n")

# FLAG SCRIPT END
    cat("gl.report.monomorphs Completed\n")
return(NULL)
}

**Comment by arthurgeorges** [comment]
Well, cutting and pasting did not work so well. Try this. Rename to a .R file.

A
[gl.report.monomorphs.txt](https://github.com/green-striped-gecko/dartR/files/2782611/gl.report.monomorphs.txt)

**Comment by RobWhite100** [comment]
Rapid response. Thanks Arthur

**Comment by arthurgeorges** [comment]
Insomniac in PNG :)
