### ISSUE TITLE
gl.filter.secondaries - doesn't recognise 'best' as a method. Bug?

### ISSUE THREAD

**Issue by AGibsonV** [green-striped-gecko/dartR#611]
Hello dartR team,

First of all, thank you for making such a comprehensive R package to manipulate and analyse DArT SNP data. It's been hugely valuable in my PhD and now in my early career. 

I would like to filter multiple SNP loci within a fragment (secondaries). Using the default method 'random', either through `gl.filter.secondaries (gl)` or by calling it directly `gl.filter.secondaries (gl, method = 'random')` works just fine. However, I would like to use the 'best' method. When calling it: `gl.filter.secondaries (gl, method = 'best')` the method is not recognised and I get an error. 
```
Starting gl.filter.secondaries 
  Processing genlight object with SNP data
  Selecting one SNP per sequence tag based on best RepAvg 
                    and AvgPIC
Error in gl.filter.secondaries(gl, method = "best") : 
  object '"best"' not found
```

The function fails to recognise this method, and so instead tries to look for an object under the name which is obviously incorrect. Given the simplicity of these early filtering steps, perhaps this is a bug? As there really is no other way for me to specify this function.

Thanks.

Windows OS 10.0.19045
R version 4.3.0

**Comment by mijangos81** [comment]
Hi,

Thank you for reporting this bug. This has been fixed and the updated version is available in the developing version of dartR which can be installed as below. 

Cheers,
Luis 

> devtools::install_github("green-striped-gecko/dartR@dev")
> library(dartR)
> gl.filter.secondaries(platypus.gl,method = "best")

**Comment by AGibsonV** [comment]
Thanks a bunch Luis! It works perfectly now.

**Comment by AGibsonV** [comment]
Thanks a bunch Luis and team for that speedy fix! It works perfectly now.
