### ISSUE TITLE
Multitest correction in HWE filter?

### ISSUE THREAD

**Issue by DaniEstevezBarcia** [green-striped-gecko/dartR#648]
Hello,

Congrats for a very fun and nice package. I wanted to check out how well the package can filter out loci out of HWE, I wanted to ask if you had incorporated any multitest correction in the analyses.

Thank you

**Comment by biomatix** [comment]
Hi Daniel,

If you mean is there an option for correcting for multiple comparisons,
then yes.

mult.comp.adj

Whether to adjust p-values for multiple comparisons [default FALSE].
mult.comp.adj.method

Method to adjust p-values for multiple comparisons: 'holm', 'hochberg',
'hommel', 'bonferroni', 'BH', 'BY', 'fdr' (see details) [default 'fdr'].

Refer to ?gl.filter.hwe

Arthur

**Comment by DaniEstevezBarcia** [comment]
Thanks Arthur
