### ISSUE TITLE
Join the read dart and dart2gl scripts into one gl.read.dart.r 

### ISSUE THREAD

**Issue by arthurgeorges** [green-striped-gecko/dartR#7]
There needs to be one script to take the DArT csv files (1-row or 2-row) and convert to a genlight object -- gl.read.dart(). At present, the user must read the DArT file in and then convert to a genlight object as a two step process. Leave the two scripts without export.

**Comment by green-striped-gecko** [comment]
done, named it currently read.dart2genlight can rename if needed

**Comment by green-striped-gecko** [comment]
renamed now.
