### ISSUE TITLE
Vector Size cannot be NA?

### ISSUE THREAD

**Issue by ejames26** [green-striped-gecko/dartR#84]
Hey Bernd,

Having some trouble with the vector.

fmat <- as.matrix(ggbfmales)[father,]
>   fhet <- sum(fmat==1)
>   father.half <- ifelse(fmat==1, sample(c(0,2), fhet, replace = T), fmat) 

Error in sample.int(length(x), size, replace, prob) : 
  vector size cannot be NA

Where am I going wrong here?

**Comment by ejames26** [comment]
I believe I found the reason.
fmat==1 has to be fmat=1

**Comment by biomatix** [comment]
Hi James,

This bug has been addressed on the dartR Google Goup page.

A
