### ISSUE TITLE
Error in gl.filter.callrate() in dartR v1.5.5

### ISSUE THREAD

**Issue by yrodger** [green-striped-gecko/dartR#87]
I just installed the new version of dartR 1.5.5 and suddenly I'm getting an error when I try to filter with gl.filter.callrate:

> gl.tvd <- gl.filter.callrate(gl.tvdf5, method="loc", threshold = 1.00)

*Error in if (x@other$loc.metrics.flags$monomorphs == FALSE) { : 
  argument is of length zero

This occurs whether method is "ind" or "loc". When I look at my gl information, gl@other$loc.metrics.flags$monomorphs it returns "NULL".

I have never come across this issue before (could be a bug in the new version?) - please advise.

**Comment by biomatix** [comment]
Hi yrodger,

Please use gl <- gl.compliance.check(gl) for all existing genlight objects
(or those read in from binary) before using scripts in the new version.

A
