### ISSUE TITLE
gl.report.pa() not working

### ISSUE THREAD

**Issue by yrodger** [green-striped-gecko/dartR#89]
Hi Arthur & Bernd,

I'm just trying to use gl.report.pa (I noticed that the previous gl.report.pa.pop has disappeared from the package) and it is not working. The table produced has pairwise populations but the N1 and N2 in every row are the total genlight population size and there are no private or fixed alleles, even for population pairs that I know have them. Just wanted to bring this to your attention in case there is a bug...

Thanks!

Yael

**Comment by chasesmith15** [comment]
Hi Arthur & Bernd,

I'm having this same issue with private alleles. It worked fine in the previous version of dartR, but running into issues now. Anyway this could be fixed?

Chase
