### ISSUE TITLE
ind.metrics File -- independent of order of OTUs

### ISSUE THREAD

**Issue by arthurgeorges** [green-striped-gecko/dartR#9]
Currently the order of the individuals in the ind.metrics file needs to match the order in the DArT input file. Need to make it so that the order of the individuals in the ind.metrics file does not matter, while retaining the checks for all individuals in the DArT file present in the ind.metrics file, and vice versa.

**Comment by green-striped-gecko** [comment]
no, this is not a requirement. should work in any order using dart2genlight and also now read.dart2genlight
Tested that (also with random order)
Try to add covariate file: d:/test/cvf.csv .
Ids of covariate file does not match the number of ids in the genetic file. Maybe this is fine if a subset matches.
Ids of covariate file (at least a subset of) are matching!
Found  20 matching ids out of 20 ids provided in the covariate file. Subsetting snps now!.
 Added pop factor.
Added latlon data.
Added  id  to the other$ind.metrics slot.
 Added  pop  to the other$ind.metrics slot.
 Added  lat  to the other$ind.metrics slot.
 Added  lon  to the other$ind.metrics slot.
 Added  sex  to the other$ind.metrics slot.
 Added  maturity  to the other$ind.metrics slot.
