### ISSUE TITLE
Reading DArT Files into a Genlight Object; Error object 'gl.read.dart' not found

### ISSUE THREAD

**Issue by farhan-lab** [green-striped-gecko/dartR#93]
Dear dartR developer,

I am trying to read SNPs data provided by Dart company as csv file and trying to covert these files to genlight object for further analysis using following command as given in the tutorial:
gl <- gl.read.dart(filename = "testset.csv", ind.metafile = " ind_metrics.csv")

but get this error 
Error: object 'gl.read.dart' not found

Could you please guide me anything is wrong and how to fix this issue?
Thanks,
Best,
Farhan

**Comment by green-striped-gecko** [comment]
Hi,

This sounds like you have not installed dartR properly.

Can you try to do:

library(dartR)

and

packageVersion("dartR")
